id: I5B5DC4BD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:24:05+00:00'
last_modified: '2022-06-08T03:43:34.709349+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28065
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་བང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4EE5:
      image_group_id: I8LS16455
      title: ''
      total_pages: 570
      order: 1
      base_file: 4EE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
