id: P005528
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28065
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་བང་མཛོད།
  author: ''
  volumes:
    b939b7f869cb49858974f9a6789b9fc1:
      image_group_id: I8LS16455
      title: ''
      volume_number: 1
      total_pages: 570
      base_file: v001.txt
